version: "3.3"
services:
  app:
    build:
      context: ../../
      dockerfile: ./images/app/Dockerfile
    command: sh -c "mvn package && java -jar target/docker-practice-java-0.0.1-SNAPSHOT.jar"
    volumes:
      - ../../:/opt/app
    ports:
      - "8888:8080"
    networks:
      - docker-practice-net
    restart: always
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: "school"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "school"
    restart: always

    networks:
      - docker-practice-net
    volumes:
      - ../../data/dump:/db-dump
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - docker-practice-net
    ports:
      - '6379:6379'

networks:
  docker-practice-net:
